package player;

import sound.Pitch;
import utilities.Fraction;

/**
 * Represents a single note. A not has pitch and duration.
 * 
 * The Note class is immutable (public final model).
 * 
 * @author woursler
 * @version RC1
 */
public class Note {
	public final Fraction duration;
	public final Pitch pitch;


	
	//TODO: Constructor for Note
	
	//TODO: all below this line is autogenerated...

	public Fraction getDuration() {
		return duration;
	}

	public void setDuration(Fraction duration) {

	public Note(Fraction duration, Pitch pitch) {
		this.duration = duration;
		this.pitch = pitch;
	}

}
