package player;

import sound.Pitch;
import utilities.Fraction;

public class Note {
	private Fraction duration;
	private Pitch pitch;
	
	//TODO: all below this line is autogenerated...
	public Fraction getDuration() {
		return duration;
	}
	public void setDuration(Fraction duration) {
		this.duration = duration;
	}
	
	public Pitch getPitch() {
		return pitch;
	}
	public void setPitch(Pitch pitch) {
		this.pitch = pitch;
	}

}
